cat << 'INNER' > fix_buttons.sed
s/<a\s*href="https:\/\/wa.me.*paket%20Personal.*"\s*target="_blank"\s*rel="noopener noreferrer"\s*className="w-full py-3 px-4 bg-indigo-50 text-indigo-700 font-bold rounded-xl text-center hover:bg-indigo-100 transition-colors"\s*>\s*Hubungi Admin\s*<\/a>/<button onClick={() => { setRegData({...regData, paket: "Personal (Rp 99.000)"}); setIsRegisterModalOpen(true); }} className="w-full py-3 px-4 bg-indigo-50 text-indigo-700 font-bold rounded-xl text-center hover:bg-indigo-100 transition-colors">Daftar Paket Personal<\/button>/g

s/<a\s*href="https:\/\/wa.me.*paket%20Sekolah.*"\s*target="_blank"\s*rel="noopener noreferrer"\s*className="w-full py-3 px-4 bg-white text-indigo-600 font-bold rounded-xl text-center hover:bg-indigo-50 transition-colors shadow-lg shadow-indigo-900\/20"\s*>\s*Hubungi Admin via WA\s*<\/a>/<button onClick={() => { setRegData({...regData, paket: "Sekolah (Rp 199.000)"}); setIsRegisterModalOpen(true); }} className="w-full py-3 px-4 bg-white text-indigo-600 font-bold rounded-xl text-center hover:bg-indigo-50 transition-colors shadow-lg shadow-indigo-900\/20">Daftar Paket Sekolah<\/button>/g
INNER
# We can use perl to handle multiline replacements easily
perl -0777 -pi -e 's/<a[^>]*href="https:\/\/wa.me[^>]*paket%20Personal[^>]*"[^>]*>(\s*)Hubungi Admin(\s*)<\/a>/<button onClick={() => { setRegData({...regData, paket: "Personal (Rp 99.000)"}); setIsRegisterModalOpen(true); }} className="w-full py-3 px-4 bg-indigo-50 text-indigo-700 font-bold rounded-xl text-center hover:bg-indigo-100 transition-colors">Daftar Paket Personal<\/button>/g' src/components/LandingPageView.tsx

perl -0777 -pi -e 's/<a[^>]*href="https:\/\/wa.me[^>]*paket%20Sekolah[^>]*"[^>]*>(\s*)Hubungi Admin via WA(\s*)<\/a>/<button onClick={() => { setRegData({...regData, paket: "Sekolah (Rp 199.000)"}); setIsRegisterModalOpen(true); }} className="w-full py-3 px-4 bg-white text-indigo-600 font-bold rounded-xl text-center hover:bg-indigo-50 transition-colors shadow-lg shadow-indigo-900\/20">Daftar Paket Sekolah<\/button>/g' src/components/LandingPageView.tsx
